
"""
AI Service module - connects to OpenAI (or compatible) to provide:
- AI tutor responses
- Quiz generation
- Research assistance
- Course & certification recommendations

Set environment variable OPENAI_API_KEY before running.
"""

import os
import json
from typing import List, Dict
import openai
from pydantic import BaseModel

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")  # change if unavailable

if not OPENAI_API_KEY:
    # openai library will still be imported, but we avoid raising here so tests can run.
    pass
else:
    openai.api_key = OPENAI_API_KEY

def _call_openai_system(user_prompt: str, system_prompt: str = "You are a helpful educational assistant.") -> str:
    """
    Call OpenAI Chat Completions synchronously and return assistant text.
    """
    if not OPENAI_API_KEY:
        # Fallback: return a deterministic placeholder when API key is not configured.
        return ("[OPENAI_API_KEY not set. To enable real AI responses, set OPENAI_API_KEY in the environment.]\n\n"
                + user_prompt[:100])
    try:
        resp = openai.ChatCompletion.create(
            model=OPENAI_MODEL,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            max_tokens=800,
            temperature=0.2,
        )
        return resp.choices[0].message.content.strip()
    except Exception as e:
        return f"[AI service error: {str(e)}]"

# ----------------------------
# Tutor
# ----------------------------
def generate_ai_tutor_response(student_id: int, message: str) -> Dict:
    """
    Generate an AI tutor response for the given message.
    Returns a dict with keys: 'answer' and 'notes'
    """
    prompt = f"""
You are an AI tutor for a student (id={student_id}). Answer the question concisely, include short explanation,
and provide 2 recommended next-steps (like reading links or exercises). Use bullet points for next-steps.

Question:
{message}
"""
    answer = _call_openai_system(prompt, system_prompt="You are a friendly expert tutor that explains clearly.")
    return {"answer": answer, "notes": "Generated by AI tutor"}

# ----------------------------
# Quiz generation
# ----------------------------
def generate_quiz_questions(topic: str, difficulty: str = "medium", num_questions: int = 5) -> List[Dict]:
    """
    Generate a quiz for the given topic. Returns a list of questions where each
    question is a dict: {question, options: [..], correct_answer, explanation}
    """
    prompt = f"""
Create {num_questions} {difficulty} difficulty multiple-choice questions (4 options each) about the topic: "{topic}".
Return the output as JSON array where each element has keys:
- question (string)
- options (array of 4 strings)
- correct_answer (one of the option strings)
- explanation (short string)

Do not include any extra commentary outside the JSON.
"""
    reply = _call_openai_system(prompt, system_prompt="You are a JSON-output question generator.")
    # Try to parse JSON from reply; if fails, do a simple best-effort extraction
    try:
        data = json.loads(reply)
        if isinstance(data, list):
            return data
    except Exception:
        # Fallback: wrap the whole reply as a single question
        return [{
            "question": f"Auto-generated fallback question about {topic}",
            "options": ["A", "B", "C", "D"],
            "correct_answer": "A",
            "explanation": "Fallback explanation - enable OPENAI_API_KEY for full features."
        }]
    return []

# ----------------------------
# Research assistant
# ----------------------------
def generate_research_assistance(research_description: str, help_type: str = "literature review") -> Dict:
    """
    Provide suggested outline, keywords, brief advice and references (URLs or paper titles).
    """
    prompt = f"""
You are a research assistant. A student needs help with: {research_description}
Produce a JSON object with keys:
- suggested_outline: list of section titles
- suggested_keywords: list of keywords
- advice: short paragraph with methodology suggestions
- references: list of strings (paper titles or URLs), up to 8 items

Return strictly JSON.
"""
    reply = _call_openai_system(prompt, system_prompt="You are a helpful research assistant who replies in JSON.")
    try:
        data = json.loads(reply)
        return data
    except Exception:
        return {
            "suggested_outline": ["Introduction", "Related Work", "Methodology", "Experiments", "Conclusion"],
            "suggested_keywords": ["placeholder-keyword"],
            "advice": "Enable OPENAI_API_KEY to get full research suggestions.",
            "references": []
        }

# ----------------------------
# Course & certification recommendations
# ----------------------------
def generate_course_recommendations(goal: str, level: str = "beginner") -> Dict:
    """
    Recommend courses and certifications for a student's career goal.
    Returns dict with keys: goal, recommendations (list of {title, provider, why, url?})
    """
    prompt = f"""
A student wants to become: {goal}
Provide 6 recommendations (courses or certifications), each with:
- title
- provider/platform
- why it's recommended (1 sentence)
- estimated effort (weeks/hours)
- canonical url if available

Return JSON: {{ "goal": "...", "recommendations": [ ... ] }}
"""
    reply = _call_openai_system(prompt, system_prompt="You are a pragmatic career course recommender.")
    try:
        data = json.loads(reply)
        return data
    except Exception:
        return {"goal": goal, "recommendations": [{"title": "Enable OPENAI_API_KEY", "provider": "AI", "why": "No key provided", "estimated_effort": "N/A", "url": ""}]}
